[project]
name = "trabalho-mat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "blue>=0.9.1",
    "dash>=2.18.2",
    "numpy>=2.1.3",
    "plotly>=5.24.1",
    "scipy==1.14.1",
]
